#
# Github pages customized 
# for dev.marianosciacco.it
#

title: "Development"
description: >
  Raccolta di tutti i lavori pubblici sviluppati fino ad oggi, tra cui progetti, siti web, software, relazioni tecniche e pubblicazioni. Tutti i diritti riservati al relativo autore.

author: Mariano Sciacco
email: marianosciacco@gmail.com
remote_theme: jekyll/minima@2.5-stable
show_excerpts: true

minima: 
  date_format: "%d %B %Y"
  social_links: 
    twitter: maxelweb
    github: maxelweb
    linkedin: marianosciacco

header_pages: 
  - my-projects.md
  - uni-projects.md