baseURL: 'http://localhost/'
title: 'Mariano Sciacco, Maxelweb'
theme: 
  - "maxelweb-theme"
defaultContentLanguage: it
disableKinds:
- taxonomy
- term

languages: 
  it: 
    languageName: Italiano
    languageCode: 'it-IT'
    title: 'Homepage'
    params:
      short: ITA
      flag: /img/lang/ita.png
    weight: 1
    contentDir: "content/italian"
    menu:
      main:
      - identifier: about
        weight: 1
        name: Chi sono
        url: "/about/"
        pre: "far fa-user"
        post: "fas fa-user-astronaut"
      - identifier: about-background
        parent: about
        weight: 1
        name: Background
        url: "/about/#background"
        pre: "fas fa-user-graduate"
      - identifier: about-skills
        parent: about
        weight: 2
        name: Skills
        url: "/about/#skills"
        pre: "fas fa-user-tie"
      - identifier: portfolio
        weight: 2
        name: Portfolio
        url: "/portfolio/"
        pre: "far fa-folder"
        post: "far fa-folder-open"
      - identifier: portfolio-publications
        parent: portfolio
        weight: 1
        name: Pubblicazioni
        url: "/publications/"
        pre: "fas fa-file-alt"
      - identifier: portfolio-projects
        parent: portfolio
        weight: 2
        name: Progetti
        url: "/projects/"
        pre: "fas fa-project-diagram"
      - identifier: github
        weight: 3
        name: Github
        url: "http://git.marianosciacco.it"
        pre: "fab fa-github-alt"
      - identifier: contacts
        weight: 4
        name: Contatti
        url: "/contacts/"
        pre: "far fa-envelope"
  en: 
    languageName: English
    languageCode: 'en-US'
    title: 'Homepage'
    params:
      short: ENG
      flag: /img/lang/eng.png
    weight: 2
    contentDir: "content/english"
    menu:
      main:
      - identifier: about
        weight: 1
        name: Chi sono
        url: "/about/"
        pre: "far fa-user"
        post: "fas fa-user-astronaut"
      - identifier: about-background
        parent: about
        weight: 1
        name: Background
        url: "/about/#background"
        pre: "fas fa-user-graduate"
      - identifier: about-skills
        parent: about
        weight: 2
        name: Skills
        url: "/about/#skills"
        pre: "fas fa-user-tie"
      - identifier: portfolio
        weight: 2
        name: Portfolio
        url: "/portfolio/"
        pre: "far fa-folder"
        post: "far fa-folder-open"
      - identifier: portfolio-publications
        parent: portfolio
        weight: 1
        name: Pubblicazioni
        url: "/publications/"
        pre: "fas fa-file-alt"
      - identifier: portfolio-projects
        parent: portfolio
        weight: 2
        name: Progetti
        url: "/projects/"
        pre: "fas fa-project-diagram"
      - identifier: github
        weight: 3
        name: Github
        url: "http://git.marianosciacco.it"
        pre: "fab fa-github-alt"
      - identifier: contacts
        weight: 4
        name: Contatti
        url: "/contacts/"
        pre: "far fa-envelope"