name = "Maxelweb Theme"
license = "Apache 2.0"
licenselink = "https://github.com/maxelweb/marianosciacco.it/blob/master/LICENSE"
description = "Personal Web Page Theme for MarianoSciacco.it"
homepage = "https://marianosciacco.it/"
tags = []
features = []
min_version = "0.109.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
