#
# Github pages customized 
# for dev.marianosciacco.it
#

title: "Development"
description: >
  All'interno di questa sezione sono presenti tutti i lavori sviluppati fino ad oggi, tra cui
  progetti, siti web, software e pubblicazioni.

author: Mariano Sciacco
email: marianosciacco@gmail.com
remote_theme: jekyll/minima@2.5-stable
show_excerpts: true

minima: 
  date_format: "%d %B %Y"
  social_links: 
    twitter: maxelweb
    github: maxelweb
    linkedin: marianosciacco

header_pages: 
  - projects.md
  - portfolio.md