#
# Github pages customized 
# for dev.marianosciacco.it
#

title: "Mariano Sciacco // Development"
description: "Progetti, Software e pubblicazioni"
author: Mariano Sciacco
email: marianosciacco@gmail.com
remote_theme: jekyll/minima
show_excerpts: false

minima: 
  date_format: "%d/%m/%Y"
  social_links: 
    twitter: maxelweb
    github: maxelweb
    linkedin: marianosciacco

header_pages: 
  - projects.md
  - portfolio.md