# name: Website Autodeploy

# on: 
#   push:
#     paths-ignore:
#     - 'docs/**'
#     - '.github/**'
#     - '**.md'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: git-ftp push
#       uses: sebastianpopp/git-ftp-action@releases/v2
#       with:
#         url: ${{ secrets.FTP_URL }}
#         user: ${{ secrets.FTP_USER }}
#         password: ${{ secrets.FTP_PWD }}
